steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/react-nodejs:${SHORT_SHA}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-central1-docker.pkg.dev/$PROJECT_ID/react-nodejs"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "react-nodejs",
        "--image",
        "us-central1-docker.pkg.dev/$PROJECT_ID/react-nodejs:${SHORT_SHA}",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
      
options:
  logging: CLOUD_LOGGING_ONLY
