steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/react-nodejs3", "-t", "gcr.io/$PROJECT_ID/react-nodejs3:latest", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/react-nodejs3"]
      
options:
  logging: CLOUD_LOGGING_ONLY
